/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_CODE_H_
# define SHADER_CODE_H_

const char *shader_frag =
 "#version 420\n"
 "out vec4 f;"
 "in vec4 gl_Color;"
 "layout(size4x32)uniform image2D imageTexture;"
 "uniform sampler2D imageSampler;"
 "layout(binding=1)uniform sampler2D shadeMe;"
 "float s(vec3 s,float g)"
 "{"
   "const float m=338688.,y=4.29497e+09;"
   "float v=mod(gl_Color.x,m*2./y)/(m*2./y);"
   "s.z=(15.-s.z)/30.;"
   "s.x/=.5625;"
   "float i=length(s)-(.1+sin(v*3.41)*1.3);"
   "if(gl_Color.x>.000157714)"
     "{"
       "s.x-=.6;"
       "s.x+=v;"
       "s.y+=v*.2;"
       "s*=mat3(cos(g),sin(g),0.,-sin(g),cos(g),0.,0.,0.,1.)*mat3(cos(g*.3),0.,sin(g*.3),0.,1.,0.,-sin(g*.3),0.,cos(g*.3));"
       "vec3 r=abs(s)-vec3(.3+sin(max(v-.5,0.)));"
       "i=min(max(r.x,max(r.y,r.z)),0.)+length(max(r,0.));"
     "}"
   "if(gl_Color.x>m*4./y)"
     "{"
       "vec2 r=vec2(length(s.xz)-.45,s.y);"
       "i=length(r)-.5;"
     "}"
   "if(gl_Color.x>m*6./y)"
     "i=length(s)-(.1+sin(max(v-.5,0.)*3.41)*1.3);"
   "if(gl_Color.x>m*8./y)"
     "i=0.;"
   "return i;"
 "}"
 "void main()"
 "{"
   "float g=gl_Color.z*10.-5.,y=gl_Color.x*3000.*10.,m=gl_Color.y*3000.*g,i=gl_Color.w;"
   "vec2 r=gl_FragCoord.xy/vec2(1280.,720.),v=vec2(.001,0.);"
   "if(gl_FragCoord.y<10)"
     "{"
       "vec4 l=texture(imageSampler,r.xy),c=l+vec4(sin(length(l.xy))*m*l.z+m*(15.-l.z),cos(length(l.xy))*m*l.z,0.,0.);"
       "vec3 z=c.xyz;"
       "vec2 w=vec2(s(z-v.xyy,y)-s(z+v.xyy,y),s(z-v.yxy,y)-s(z+v.yxy,y));"
       "if(s(z,y)<0.)"
         "c.xy-=normalize(w)*m*8.*sign(g);"
       "float x=0.;"
       "for(float e=0.;e<50.;e+=1.)"
         "{"
           "float b=s(z+e*normalize(vec3(0.,0.,1.)-z)/50.,y);"
           "if(b<0.)"
             "x+=1.;"
         "}"
       "c.xy=mod(c.xy+vec2(1.),2.)-vec2(1.);"
       "c.w=x/50.;"
       "imageStore(imageTexture,ivec2(gl_FragCoord.xy),c);"
     "}"
   "vec4 l=clamp(vec4(r.y,r.y,r.y,1.)+texture(shadeMe,r.xy)*i,0.,1.);"
   "float z=1.-l.x,c=l.x;"
   "vec4 x=vec4(.27451,.54902,1.,1.),e=vec4(1.,.784314,.243137,1.);"
   "l=mix(mix(l,l*x,z),mix(l*e,l,c),c);"
   "f=l;"
 "}";

#endif // SHADER_CODE_H_
